name: Docker Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t bernn:latest .

      - name: Test Python environment
        run: |
          docker run --rm bernn:latest python3 -c "import numpy; import torch; import tensorflow; import mlflow; print('All core dependencies imported successfully')"

      - name: Test R environment
        run: |
          docker run --rm bernn:latest R -e "library(harmony); library(sva); library(zinbwave); print('All R packages loaded successfully')"

      - name: Login to DockerHub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to DockerHub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker tag bernn:latest ${{ secrets.DOCKERHUB_USERNAME }}/bernn:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bernn:latest 